<!doctype html>
<html lang="fr"><head><meta charset="utf-8"><style>
@page { margin: 16mm; } body { font-family: DejaVu Sans, sans-serif; color:#292724; font-size:10pt; line-height:1.45; }
h1,h2 { margin:0; font-weight:normal; } h1 { font-size:25pt; } h2 { font-size:16pt; margin:24px 0 10px; }
.muted { color:#6b6863; } .head { border-bottom:1px solid #d8d2c7; padding-bottom:22px; } .meta { float:right; text-align:right; } .clear { clear:both; }
.parties { width:100%; margin-top:25px; } .parties td { width:50%; vertical-align:top; } .parties h2 { margin-top:0; }
.intro { margin:28px 0; white-space:pre-line; } table.lines { width:100%; border-collapse:collapse; } .lines th { background:#353330; color:#fff; padding:9px; text-align:left; font-weight:normal; } .lines td { padding:11px 9px; vertical-align:top; border-bottom:1px solid #dfdbd4; } .amount { text-align:right; white-space:nowrap; } .type { width:14%; } .price { width:15%; } .quantity { width:10%; } .total { width:15%; }
.totals { width:100%; margin-top:18px; } .totals td { vertical-align:top; } .summary { width:38%; margin-left:auto; border-collapse:collapse; } .summary td { padding:4px 9px; text-align:right; } .summary .final td { padding-top:9px; border-top:1px solid #999; font-size:12pt; font-weight:bold; }
.bottom { width:100%; margin-top:36px; } .bottom td { width:50%; vertical-align:top; } .signature { border-bottom:1px solid #bbb; height:58px; }
</style></head><body>
<div class="head"><div class="meta">Devis {{ $quote->reference }}<br><span class="muted">Émis le {{ $quote->issued_on?->format('d/m/Y') ?? '—' }}@if($quote->valid_until)<br>Valable jusqu’au {{ $quote->valid_until->format('d/m/Y') }}@endif</span></div><h1>{{ $issuer['display_name'] }}</h1><div class="muted">{{ $quote->title }}</div><div class="clear"></div></div>
<table class="parties"><tr><td><h2>Émetteur</h2><strong>{{ $issuer['legal_name'] }}</strong><br>@if($issuer['contact_name']){{ $issuer['contact_name'] }}<br>@endif{{ $issuer['address_line_1'] }}<br>@if($issuer['address_line_2']){{ $issuer['address_line_2'] }}<br>@endif{{ $issuer['postal_code'] }} {{ $issuer['city'] }}<br>{{ $issuer['country_code'] }}<br>@if($issuer['registration_number'])SIRET / immatriculation : {{ $issuer['registration_number'] }}<br>@endif@if($issuer['vat_number'])TVA : {{ $issuer['vat_number'] }}<br>@endif{{ $issuer['email'] }}</td><td><h2>Destinataire</h2><strong>{{ $recipient['name'] }}</strong><br>@if($recipient['address_line_1']){{ $recipient['address_line_1'] }}<br>@endif@if($recipient['address_line_2']){{ $recipient['address_line_2'] }}<br>@endif@if($recipient['postal_code'] || $recipient['city']){{ $recipient['postal_code'] }} {{ $recipient['city'] }}<br>@endif@if($recipient['country_code']){{ $recipient['country_code'] }}<br>@endif{{ $recipient['email'] }}</td></tr></table>
@if($quote->introduction)<div class="intro">{{ $quote->introduction }}</div>@endif
<h2>Détail</h2><table class="lines"><thead><tr><th class="type">Type</th><th>Description</th><th class="price amount">Prix unitaire</th><th class="quantity amount">Quantité</th><th class="total amount">Total</th></tr></thead><tbody>@foreach($quote->lines as $line)<tr><td>{{ ['service'=>'Prestation','product'=>'Produit','rental'=>'Location','fee'=>'Frais'][$line->kind] ?? $line->kind }}</td><td>{!! nl2br(e($line->description)) !!}</td><td class="amount">{{ number_format((float)$line->unit_amount, 2, ',', ' ') }} €</td><td class="amount">{{ rtrim(rtrim(number_format((float)$line->quantity, 2, ',', ' '),'0'),',') }}</td><td class="amount">{{ number_format((float)$line->total_amount, 2, ',', ' ') }} €</td></tr>@endforeach</tbody></table>
<table class="totals"><tr><td class="muted">{{ $quote->tax_note }}@if($quoteSettings?->terms_url)<br>CGV : {{ $quoteSettings->terms_url }}@endif</td><td><table class="summary"><tr><td>Total</td><td>{{ number_format((float)$quote->subtotal_amount, 2, ',', ' ') }} €</td></tr>@if((float)$quote->discount_amount > 0)<tr><td>Remise globale</td><td>− {{ number_format((float)$quote->discount_amount, 2, ',', ' ') }} €</td></tr>@endif<tr class="final"><td>Total final</td><td>{{ number_format((float)$quote->total_amount, 2, ',', ' ') }} €</td></tr></table></td></tr></table>
<table class="bottom"><tr><td><h2>Conditions</h2>{!! nl2br(e($quote->payment_terms ?: '')) !!}</td><td><h2>Bon pour accord</h2>À ____________________, le ____ / ____ / ______<br><br>Signature et cachet<div class="signature"></div></td></tr></table>
@if($issuer['legal_notice'])<p class="muted" style="margin-top:28px">{{ $issuer['legal_notice'] }}</p>@endif
</body></html>
