<!doctype html>
<html lang="fr"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title>Documents de location</title><style>body{margin:0;background:#f7f5f2;color:#292724;font:16px/1.5 system-ui,-apple-system,sans-serif}.box{max-width:720px;margin:48px auto;background:white;padding:38px;border-radius:14px;box-shadow:0 8px 30px #302c2518}h1{margin-top:0;font-size:28px}a{color:#155e75}.doc{border-top:1px solid #e4dfd7;padding:14px 0}.muted{color:#6b6863;font-size:14px}.notice{padding:12px 14px;border-radius:8px;margin:18px 0}.success{background:#ecfdf3;color:#166534}.error{background:#fef2f2;color:#991b1b}label{display:block;margin:16px 0 7px;font-weight:600}input[type=text]{box-sizing:border-box;width:100%;padding:11px;border:1px solid #bdb7ad;border-radius:7px;font:inherit}button{background:#272522;color:white;padding:12px 17px;border:0;border-radius:7px;font:inherit;cursor:pointer}.check{display:flex;gap:9px;font-weight:normal;align-items:flex-start}.check input{margin-top:6px}</style></head><body><main class="box">
<p class="muted">{{ $acceptance->rental->organization->name }}</p><h1>Documents de location</h1>
@if(session('success'))<div class="notice success">{{ session('success') }}</div>@endif
@if(session('error'))<div class="notice error">{{ session('error') }}</div>@endif
<p>Bonjour {{ $acceptance->recipient_name }}, veuillez consulter les documents associés à la location <strong>{{ $acceptance->rental->reference }}</strong>.</p>
@foreach($acceptance->documents as $document)<div class="doc"><strong>{{ $document->type->getLabel() }}</strong><br><a href="{{ route('rental-acceptance.document', ['token' => $token, 'document' => $document->id]) }}">Télécharger le PDF</a></div>@endforeach
@if($acceptance->status->value === 'accepted')<div class="notice success">Acceptation enregistrée le {{ $acceptance->accepted_at->format('d/m/Y à H:i') }} au nom de {{ $acceptance->accepted_name }}.</div>
@else
<form method="post" action="{{ route('rental-acceptance.accept', ['token' => $token]) }}">@csrf<label for="accepted_name">Votre nom complet</label><input id="accepted_name" name="accepted_name" type="text" value="{{ old('accepted_name', $acceptance->recipient_name) }}" required>@error('accepted_name')<div class="notice error">{{ $message }}</div>@enderror<label class="check"><input name="consent" type="checkbox" value="1" required><span>{{ $acceptance->consent_text }}</span></label>@error('consent')<div class="notice error">{{ $message }}</div>@enderror<button type="submit">Confirmer mon acceptation</button></form>
@endif
<p class="muted">Ce lien expire le {{ $acceptance->expires_at->format('d/m/Y à H:i') }}. Cette acceptation est enregistrée dans Cremona et ne constitue pas une signature électronique qualifiée.</p>
</main></body></html>
