<!doctype html>
<html lang="fr"><head><meta charset="utf-8"><style>
@page { margin: 15mm 16mm; } body { font-family: DejaVu Sans, sans-serif; color:#282623; font-size:9.1pt; line-height:1.36; } h1 { font-size:17pt; letter-spacing:.2px; margin:22px 0 18px; } h2 { font-size:11.5pt; margin:16px 0 6px; } .issuer { border-bottom:1px solid #bdb7ad; padding-bottom:11px; font-size:8.7pt; line-height:1.4; } .issuer strong { font-size:11pt; } .meta { width:100%; border-collapse:collapse; margin:12px 0 17px; } .meta td { width:50%; vertical-align:top; padding:7px 9px; border:1px solid #d8d2c8; } .label { display:block; color:#706b63; font-size:7.7pt; text-transform:uppercase; letter-spacing:.35px; margin-bottom:2px; } p { margin:0 0 8px; text-align:justify; } ul { margin:3px 0 8px 18px; padding:0; } li { margin-bottom:3px; } .signature { margin-top:21px; width:100%; border-collapse:collapse; } .signature td { width:50%; vertical-align:top; padding-right:16px; } .line { height:42px; border-bottom:1px solid #777; } .muted { color:#706b63; font-size:8pt; }
</style></head><body>
@php
    $issuer = $snapshot['issuer'];
    $client = $snapshot['client'];
    $rental = $snapshot['rental'];
    $instrument = $snapshot['instrument'];
@endphp
<div class="issuer"><strong>{{ $issuer['legal_name'] ?: $issuer['display_name'] }}</strong><br>{{ $issuer['address_line_1'] }}@if($issuer['address_line_2'])<br>{{ $issuer['address_line_2'] }}@endif<br>{{ $issuer['postal_code'] }} {{ $issuer['city'] }}@if($issuer['phone'])<br>{{ $issuer['phone'] }}@endif @if($issuer['email']) · {{ $issuer['email'] }}@endif@if($issuer['registration_number'])<br>SIRET / immatriculation : {{ $issuer['registration_number'] }}@endif</div>
<h1>{{ match ($type) { \App\Enums\RentalDocumentType::RentalContract => 'CONTRAT DE LOCATION D’INSTRUMENT DE MUSIQUE', \App\Enums\RentalDocumentType::InsuranceContract => 'CONTRAT D’ASSURANCE — INSTRUMENT EN LOCATION', \App\Enums\RentalDocumentType::ReturnCertificate => 'ATTESTATION DE RESTITUTION' } }}</h1>
<table class="meta"><tr><td><span class="label">Locataire</span><strong>{{ $client['name'] }}</strong><br>{{ $client['address_line_1'] }}@if($client['address_line_2'])<br>{{ $client['address_line_2'] }}@endif<br>{{ $client['postal_code'] }} {{ $client['city'] }}<br>{{ $client['phone'] }}<br>{{ $client['email'] }}</td><td><span class="label">Location</span><strong>Contrat {{ $rental['reference'] }}</strong><br>Instrument : {{ $instrument['name'] }}@if($instrument['reference'])<br>Référence instrument : {{ $instrument['reference'] }}@endif<br>Début prévu : {{ $rental['starts_on'] }}<br>{{ $type === \App\Enums\RentalDocumentType::RentalContract ? 'Loyer mensuel : '.$rental['monthly_amount'].' €' : 'Formule : '.($rental['insurance_plan_name'] ?: '—').' — Assurance mensuelle : '.$rental['insurance_monthly_amount'].' €' }}</td></tr></table>
@if($type === \App\Enums\RentalDocumentType::RentalContract)
<h2>Objet et durée du contrat</h2><p>Le présent contrat est établi entre le locataire et le propriétaire pour la location de l’instrument désigné ci-dessus, avec ses accessoires éventuels. Toute forme de location-achat est exclue : le propriétaire conserve la propriété du matériel, quelle que soit la durée de la location.</p><p>La location est conclue pour une durée indéterminée, avec un engagement initial de trois mois. En cas de retour anticipé, le montant correspondant à trois mois reste exigible. Le locataire indique son nom, le numéro d’instrument ou le numéro de contrat dans ses communications avec l’atelier.</p>
<h2>Tarifs, paiement et caution</h2><p>Le premier mois est réglé au prorata lors de la remise de l’instrument ; les échéances suivantes sont prélevées au début de chaque mois. Aucun dépôt de garantie n’est demandé. Le loyer et, le cas échéant, la prime d’assurance pourront être révisés chaque année au 1er septembre. Les cordes et le reméchage de l’archet restent à la charge du locataire.</p>
@if($rental['insurance_plan_name'])
<p>Cette location comprend la formule d’assurance <strong>{{ $rental['insurance_plan_name'] }}</strong> ({{ $rental['insurance_monthly_amount'] }} € par mois). Le montant mensuel global à régler est de <strong>{{ $rental['total_monthly_amount'] }} €</strong>.</p>
@endif
<h2>Résiliation</h2><p>À partir du quatrième mois, le locataire peut résilier par courrier ou e-mail. La résiliation prend effet lors de la restitution du matériel à l’atelier ; tout mois commencé est dû. Les frais restant à la charge du locataire sont réglés lors de cette restitution.</p><p>Trois mois consécutifs impayés sans nouvelles du locataire entraînent la résiliation immédiate et l’obligation de restituer le matériel et de régler les impayés. Le propriétaire peut aussi résilier en cas de défauts de paiement répétés, de rejets de prélèvement ou de dégradation excessive, après notification par lettre recommandée avec accusé de réception.</p>
<h2>Engagement de l’atelier</h2><p>L’atelier assure une révision annuelle, les réglages et les retouches de vernis, sauf mauvais entretien manifeste. Un changement de taille peut être demandé à tout moment ; l’atelier s’efforce alors de fournir un instrument adapté. Les accessoires peuvent être échangés en tenant compte de leur usure normale. Le locataire reconnaît recevoir un matériel en état de fonctionnement.</p>
<h2>Engagement du locataire</h2><p>Le locataire transmet tout changement de coordonnées bancaires, d’adresse ou de téléphone. Il respecte les échéances et rembourse les frais bancaires liés à un rejet. Il permet la révision périodique de l’instrument et de l’archet ; une fréquence annuelle est recommandée. Pour une location de deux ans ou plus sans révision, un jeu de cordes neuf et le reméchage peuvent être facturés lors du retour. Les réparations sont effectuées par l’atelier sauf accord préalable.</p>
<h2>Données personnelles et pièces à fournir</h2><p>Pour la signature, le locataire fournit une pièce d’identité, un justificatif de domicile et, le cas échéant, un mandat SEPA. L’atelier conserve les seules données nécessaires à la gestion du contrat dans des conditions de sécurité appropriées et ne les diffuse pas à des tiers à des fins commerciales.</p>
@elseif($type === \App\Enums\RentalDocumentType::InsuranceContract)
<p>Le présent contrat complète la location de l’instrument désigné ci-dessus. Sa durée correspond à celle de cette location.</p>
<h2>Garanties</h2><p>L’instrument et ses accessoires sont garantis contre le bris accidentel, le vol, la perte, l’incendie et le dégât des eaux. L’assurance est valable dans le cadre de l’activité musicale, à l’habitation, dans les locaux scolaires et salles de spectacle, ainsi que pendant les déplacements en France métropolitaine.</p>
@if($rental['insurance_clause_version'] || $rental['insurance_coverage_summary'])
<p><strong>Référence de garanties{{ $rental['insurance_clause_version'] ? ' : '.$rental['insurance_clause_version'] : '' }}</strong>{!! $rental['insurance_coverage_summary'] ? '<br>'.e($rental['insurance_coverage_summary']) : '' !!}</p>
@endif
<h2>Exclusions et franchise</h2><ul><li>Vol ou endommagement d’un instrument laissé dans un véhicule.</li><li>Utilisation non conforme ou négligente du matériel loué.</li><li>Cordes et mèche de l’archet.</li></ul><p>En cas de sinistre, une franchise de 10 % de la facture de réparation ou de la valeur de remplacement reste à la charge du locataire lorsque le matériel est irréparable, perdu ou volé.</p>
<h2>Déclaration et facturation</h2><p>Le locataire déclare le sinistre à l’atelier par lettre recommandée avec accusé de réception dans un délai maximal de cinq jours. L’atelier met tout en œuvre pour fournir un instrument de remplacement dans les meilleurs délais. Cette assurance est facturée mensuellement et s’ajoute au loyer dans le prélèvement global.</p>
@else
<h2>Restitution</h2><p>L’atelier atteste avoir reçu le {{ $snapshot['return']['returned_on'] }} l’instrument désigné ci-dessus et les éléments décrits dans le présent constat.</p>
<h2>Accessoires</h2><p>{{ $snapshot['return']['accessories_state'] ?: 'Aucune observation renseignée.' }}</p>
<h2>État et observations</h2><p>{{ $snapshot['return']['condition_notes'] ?: 'Aucune observation renseignée.' }}</p>
<h2>Frais éventuels</h2><p>@if((float) str_replace(',', '.', str_replace(' ', '', $snapshot['return']['charge_amount'])) > 0){{ $snapshot['return']['charge_amount'] }} € — {{ $snapshot['return']['charge_note'] ?: 'Motif à préciser.' }}@else Aucun frais déclaré lors de la restitution.@endif</p>
@endif
<h2>Acceptation</h2><p>En signant ce document, le locataire déclare accepter sans réserve les clauses ci-dessus.</p>
<table class="signature"><tr><td>Fait le {{ $snapshot['generated_on'] }}<br><br>Le propriétaire<div class="line"></div></td><td>Lu et approuvé, date et signature du locataire<div class="line"></div></td></tr></table>
<p class="muted">Document généré le {{ $snapshot['generated_on'] }}. La signature électronique et son prestataire restent distincts de cette génération et de cet archivage.</p>
</body></html>
